# Deploy MKTXP to Dockerhub
# Original Repo: 

name: Docker Builds

# Controls when the workflow will run
on:
  push:

# Run for every new Release
# on:
#  release:
#    types: [published]

permissions: 
  contents: read
  # packages: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'akpw/mktxp.git'
          ref: 'main'
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: leonmorten/mktxp:latest

